---
title: "Hello, Penguins!"
author: ""
format: html
editor: visual
---

<!-- The block above (between the `---` lines) is the YAML header. -->
<!-- Markdown heading: lines starting with `##` are Heading 2, like the one below. -->

## Data

For this analysis we'll use the penguins dataset from the palmerpenguins R package.

```{r}
#| label: load-packages
#| message: false

library(tidyverse)
library(ggthemes)
library(palmerpenguins)
library(gt)
```

## Species

The figure below is a scatterplot of species of penguins.

<!-- The chunk below is a code chunk: starts with ```{r}, ends with ``` -->

```{r}
#| label: bill-dims-species
#| warning: false

ggplot(data = penguins,
       # EDIT TARGET (a): change `bill_length_mm` to `flipper_length_mm`
       mapping = aes(x = bill_length_mm,
                     y = bill_depth_mm,
                     color = species,
                     shape = species)) +
  geom_point() +
  scale_color_colorblind() +
  labs(x = "Bill length (mm)", y = "Bill depth (mm)") +
  theme_minimal()
```

## Penguins

The table below shows the first 10 penguins from the dataset.

```{r}
#| label: penguins-top10

penguins |>
  # EDIT TARGET (b): change `n = 10` to `n = 5`
  slice_head(n = 10) |>
  select(species, island, bill_length_mm, bill_depth_mm) |>
  gt()
```
